version: '3.8'

services:
  # 메인 애플리케이션 (Docker Hub 이미지 사용)
  app:
    image: ${DOCKER_HUB_USERNAME:-mindbuddy}/mindbuddy-app:${TAG:-latest}
    container_name: mindbuddy-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mindbuddy
      - JWT_SECRET=${JWT_SECRET:-mindBuddySecretKey2025SecureApplicationForCounseling}
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3000
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mindbuddy-network
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs

  # AI 매칭 서비스 (Docker Hub 이미지 사용)
  ai-matching-service:
    image: ${DOCKER_HUB_USERNAME:-mindbuddy}/mindbuddy-ai-matching:${TAG:-latest}
    container_name: mindbuddy-ai-matching
    restart: unless-stopped
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - redis
    networks:
      - mindbuddy-network

  # 감정 분석 서비스 (Docker Hub 이미지 사용)
  sentiment-service:
    image: ${DOCKER_HUB_USERNAME:-mindbuddy}/mindbuddy-sentiment:${TAG:-latest}
    container_name: mindbuddy-sentiment
    restart: unless-stopped
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - redis
    networks:
      - mindbuddy-network

  # React 프론트엔드 (Docker Hub 이미지 사용)
  frontend:
    image: ${DOCKER_HUB_USERNAME:-mindbuddy}/mindbuddy-frontend:${TAG:-latest}
    container_name: mindbuddy-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_SERVER_URL=""
    depends_on:
      - app
    networks:
      - mindbuddy-network

  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: mindbuddy-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=mindbuddy
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
    networks:
      - mindbuddy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d mindbuddy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: mindbuddy-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mindbuddy-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx 로드 밸런서
  nginx:
    image: nginx:alpine
    container_name: mindbuddy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
      - frontend
    networks:
      - mindbuddy-network
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:
  app_uploads:
  app_logs:

networks:
  mindbuddy-network:
    driver: bridge