groups:
  - name: mindbuddy-alerts
    rules:
      # 높은 응답 시간 알림
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "높은 응답 시간 감지"
          description: "95th percentile 응답 시간이 1초를 초과했습니다: {{ $value }}초"

      # 높은 에러율 알림
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"4..|5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "높은 에러율 감지"
          description: "에러율이 5%를 초과했습니다: {{ $value }}%"

      # 메모리 사용량 알림
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 512
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "높은 메모리 사용량"
          description: "메모리 사용량이 512MB를 초과했습니다: {{ $value }}MB"

      # CPU 사용률 알림
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "높은 CPU 사용률"
          description: "CPU 사용률이 80%를 초과했습니다: {{ $value }}%"

      # 서비스 다운 알림
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "서비스 다운"
          description: "{{ $labels.job }} 서비스가 다운되었습니다"

      # 데이터베이스 연결 실패
      - alert: DatabaseConnectionFailed
        expr: mongodb_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "데이터베이스 연결 실패"
          description: "MongoDB 연결이 실패했습니다"