name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand({ping: 1})' | mongo --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Wait for MongoDB
      run: |
        sleep 15
        # MongoDB가 준비될 때까지 대기
        for i in {1..30}; do
          if nc -z localhost 27017; then
            echo "MongoDB is ready!"
            break
          fi
          echo "Waiting for MongoDB... ($i/30)"
          sleep 2
        done

    - name: Verify test setup
      run: |
        echo "Node.js version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "MongoDB connection test..."
        
    - name: Run tests
      run: |
        # 테스트 재시도 로직
        for i in {1..3}; do
          echo "Test attempt $i/3"
          if npm test; then
            echo "Tests passed on attempt $i"
            break
          elif [ $i -eq 3 ]; then
            echo "Tests failed after 3 attempts"
            exit 1
          else
            echo "Test attempt $i failed, retrying..."
            sleep 5
          fi
        done
      env:
        NODE_ENV: test
        JWT_SECRET: test-jwt-secret-for-ci
        MONGODB_URI: mongodb://localhost:27017/mindbuddy-test
        CI: true
        FORCE_COLOR: 0

    - name: Generate test coverage
      run: npm run test:coverage
      continue-on-error: true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies for security scan
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate || true

    - name: Run Snyk to check for vulnerabilities
      if: ${{ secrets.SNYK_TOKEN }}
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [test, security-scan]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build --if-present

    - name: Build Docker images
      run: |
        if [ -f "Dockerfile.backend" ]; then
          docker build -f Dockerfile.backend -t mindbuddy-backend:${{ github.sha }} .
        fi
        if [ -f "Dockerfile.frontend" ]; then
          docker build -f Dockerfile.frontend -t mindbuddy-frontend:${{ github.sha }} .
        fi

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # 실제 배포 스크립트는 여기에 추가

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production environment..."
        # 실제 배포 스크립트는 여기에 추가