name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint:report
      continue-on-error: true

    - name: Run Prettier check
      run: npm run format:check
      continue-on-error: true

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          
          let comment = '## 코드 품질 검사 결과\n\n';
          
          // ESLint 결과 추가
          if (fs.existsSync('eslint-report.json')) {
            const eslintReport = JSON.parse(fs.readFileSync('eslint-report.json', 'utf8'));
            const errorCount = eslintReport.reduce((sum, file) => sum + file.errorCount, 0);
            const warningCount = eslintReport.reduce((sum, file) => sum + file.warningCount, 0);
            
            comment += `### ESLint 결과\n`;
            comment += `- 오류: ${errorCount}개\n`;
            comment += `- 경고: ${warningCount}개\n\n`;
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });