name: Docker Hub Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      docker_hub_username:
        description: 'Docker Hub Username'
        required: true
        default: 'mindbuddy'
      tag:
        description: 'Image Tag'
        required: true
        default: 'latest'

env:
  DOCKER_HUB_USERNAME: ${{ github.event.inputs.docker_hub_username || 'mindbuddy' }}
  TAG: ${{ github.event.inputs.tag || 'latest' }}

jobs:
  docker-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push images (if not PR)
      if: github.event_name != 'pull_request'
      run: |
        export DOCKER_HUB_USERNAME="${{ secrets.DOCKER_HUB_USERNAME || env.DOCKER_HUB_USERNAME }}"
        export TAG="${{ env.TAG }}"
        ./scripts/docker-build-push.sh
    
    - name: Test Docker Hub images
      run: |
        export DOCKER_HUB_USERNAME="${{ secrets.DOCKER_HUB_USERNAME || env.DOCKER_HUB_USERNAME }}"
        export TAG="${{ env.TAG }}"
        export TIMEOUT=120
        ./scripts/docker-ci-test.sh
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: docker-test-logs
        path: |
          docker-compose.hub.yml
          .env.hub
        retention-days: 7

  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_HUB_USERNAME || env.DOCKER_HUB_USERNAME }}/mindbuddy-app:${{ env.TAG }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'